### ISSUE TITLE
Can't select starting room

### ISSUE THREAD

**Issue by SovietJazzLord** [Jerry-Licious/force-key#1]
As the title says, i can't select my starting room when i jump into act 3. Everything works just fine, i can click on my deck, close and open the map, etc etc.

![image](https://user-images.githubusercontent.com/90869863/133680437-ef167e10-30fb-4ab2-8981-0ed33af45346.png)

**Comment by Jerry-licious** [comment]
Sorry for being a whole month late, on the first glance it seems like that the mod is locking you out of the map when you don't have keys enabled, looking into it!

**Comment by Jerry-Licious** [comment]
Uploading new version soon!

**Comment by Jerry-licious** [comment]
New version shipped!
